# Generated by Django 4.2.5 on 2024-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField(max_length=1000)),
                ("last_polled", models.DateTimeField(blank=True, null=True)),
                ("recipients", models.CharField(max_length=1000)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
