# Generated by Django 4.2.5 on 2024-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upwork", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfeed",
            name="assistant_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="jobfeed",
            name="assistant_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobfeed",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
