version: '3'

include:
  - local.yml

services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./compose/local/ngrok/ngrok.yml:/etc/ngrok.yml
    environment:
      - NGROK_ENABLED=True
    ports:
      - "4040:4040"
