# Generated by Django 4.2.5 on 2024-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("request_method", models.PositiveSmallIntegerField(choices=[(0, "GET"), (1, "POST")])),
                ("response_status_code", models.PositiveSmallIntegerField()),
                ("last_checked", models.DateTimeField()),
                ("last_success", models.DateTimeField()),
                ("last_failure", models.DateTimeField()),
                ("last_notified", models.DateTimeField()),
            ],
        ),
    ]
